version: "3.8"

services:
  culltique:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: culltique
    ports:
      - "8000:8000"
    env_file: 
      - .env  # Root level .env file
    environment:
      # Override or add any additional environment variables here
      PYTHONPATH: /app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 40s