[project]
name = "ecommerce-apis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.115.14",
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.35.0",
]
